### ISSUE TITLE
TextBox DB 연동 및 floating 

### ISSUE THREAD

**Issue by gus1043** [MobileComputing-2023/AI-PictureBook#67]
## 작업 상세 내용
- [x] Draw 페이지에 textbox floating 
- [x] DB에 textbox 관련 정보(위치, 색) 저장 기능(이미지로 저장해도 될 것 같기도 함)
- [x] Read 페이지에 textbox 띄우기
## 참고 사항
-
-

**Comment by KimSH39** [comment]
DB에 textbox 관련 정보 저장 -> textbox fragment bitmap 변환 + y 좌표 db 저장 후 read에서 띄우는 쪽으로
